### ISSUE TITLE
Seek code

### ISSUE THREAD

**Issue by Hongyi584** [duweidai/Ms-RED#2]
Hello, when will you release the code?

**Comment by duweidai** [comment]
发自我的iPhone


------------------ Original ------------------
From: Hongyi584 ***@***.***&gt;
Date: Mon,Dec 6,2021 3:32 PM
To: duweidai/Ms-RED ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [duweidai/Ms-RED] Seek code (Issue #2)





 
Closed #2.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by duweidai** [comment]
Thank you very much for your affirm. We will publish the code related to Ms RED on January 1, 2022.



发自我的iPhone


------------------ Original ------------------
From: Hongyi584 ***@***.***&gt;
Date: Mon,Dec 6,2021 3:31 PM
To: duweidai/Ms-RED ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [duweidai/Ms-RED] Seek code (Issue #2)





 
Hello, when will you release the code?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
